# Generated by Django 5.2.6 on 2025-09-10 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventosDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizadoresDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.EmailField(max_length=254, unique=50)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizadores', to='eventos.eventosdb')),
            ],
        ),
    ]
